[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "npm install --prefer-offline --no-audit --no-fund"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npx serve -s build -l $PORT"

[variables]
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"